AsgardCms/Platform

composer.json
This line is not needed, because it has no effect.
php artisan asgard:install will generate the correct key
=> Removed Key Generation

Modules/User/Events/UserIsUpdating.php, Modules/User/Events/UserWasCreated.php, Modules/User/Repositories/Sentinel/SentinelUserRepository.php
The `save` method (which `update` calls), only returns boolean.
Also changed around the `create` and `createWithRoles` methods so activation email isn't sent if the boolean `$activated` is `true`.
This PR also includes a new event that fires before saving when updating.
=> Fix the UserWasUpdated event only receiving boolean on update

Modules/Workshop/Scaffold/Module/ModuleScaffold.php
https://github.com/AsgardCms/Core/tree/2.0 and https://github.com/Idavoll/Core/tree/2.0 are out of sync now.
=> When scaffolding new modules, use the new namespace for the Core module

Modules/Core/Config/permissions.php, Modules/Core/Sidebar/SidebarExtender.php, Modules/Translation/Resources/lang/core/en/sidebar.php, Modules/Translation/Resources/lang/workshop/en/themes.php, Modules/Translation/Resources/lang/workshop/en/workshop.php, Modules/User/Database/Seeders/SentinelGroupSeedTableSeeder.php, Modules/Workshop/Config/permissions.php, Modules/Workshop/Sidebar/SidebarExtender.php
Closes #276
- Add missing language line for workshop themes
- Add missing permissions from AsgardCms/Workshop#31 to permissions seed
- Add Workshop permission to globally turn on/off sidebar group
- Remove permissions check on core sidebar group
- Sort permission seeder in order of permissions config file
=> Add sidebar permissions to allow turning groups on/off globally

Modules/Core/macros.php
Input with number zero return empty value:
For instance: $object->test = 0
```php
{!! Form:: normalInput('test', 'Test', $errors, $object) !!} 
```
Result:
```php
<input class="form-control" placeholder="Test" name="test" type="text" value="">
```
Instead of
```php
<input class="form-control" placeholder="Test" name="test" type="text" value="0">
```
Same for 
```php
{!! Form:: normalTextarea('test', 'Test', $errors, $object) !!} 
```
Return empty value instead of 0
=> Input issue when number is zero

Modules/User/Repositories/Sentinel/SentinelUserRepository.php
When updating a user via "My Account -> Profile", if the password field was blank it would remove the user's password completely. If the user changed their password, it would be saved to the database **without** being hashed first.
=> Check for password change when updating user

Modules/User/Repositories/Sentinel/SentinelUserRepository.php
This fixes errors introduced in #294, if the request data does not contain a password field.
=> Check if ‘password’ key exists before unsetting

Modules/Translation/Resources/lang/user/en/messages.php, Modules/User/Emails/ResetPasswordEmail.php, Modules/User/Emails/WelcomeEmail.php
Also has a side effect of adding compatibility with Laravel =< 5.3.29, if the tests would also pass…
=> Allow user Welcome and Password Reset email subjects to be translated

Modules/Translation/Resources/lang/user/en/users.php, Modules/User/Http/Controllers/Admin/Account/ApiKeysController.php
Fixing typo error for lang
1) Fixing a typo error for success message
2) Use individual success message for deleting an API key
With this change everyone can add his own translations
=> Kay899 patch 1

Modules/Setting/Http/Controllers/Admin/SettingController.php
See https://laravel.com/docs/5.4/upgrade
->set() method should be changed to ->put()
....
Sessions:Symfony Compatibility
Laravel's session handlers no longer implements Symfony's SessionInterface. Implementing this interface required us to implement extraneous features that were not needed by the framework. Instead, a new Illuminate\Contracts\Session\Session interface has been defined and may be used instead. The following code changes should also be applied:
All calls to the ->set() method should be changed to ->put(). Typically, Laravel applications would never call the set method since it has never been documented within the Laravel documentation. However, it is included here out of caution.
All calls to the ->getToken() method should be changed to ->token().
All calls to the …
=> Update to Laravel 5.4 Sessions:Symfony Compatibility

Modules/Translation/Repositories/Eloquent/EloquentTranslationRepository.php
When i tried to use "Translator", i figured out that the "EloquentTranslationRepository::findByKeyAndLocale" is using wrong clause for fetching the result of the translation record in database.
For example,
```php
public function findByKeyAndLocale($key, $locale = null)
{
$locale = $locale ?: app()->getLocale();
// when using "whereKey" clause, it will always return null. 
// coz, it's fetching the id instead of "key" field.
$translation = $this->model->whereKey($key)->with('translations')->first();
// its now getting the result correctly.
$translation = $this->model->where('key', $key)->with('translations')->first();
if ($translation && $translation->hasTranslation($locale)) {
return $translation->translate($locale)->value;
}
return '';
} 
```
And also reference to …
=> use “where” clause for fetching translation by key instead of “whereKey”

Modules/Workshop/Config/config.php, Modules/Workshop/Scaffold/Module/Generators/Generator.php
By this change we would be able to define a custom path where to store customized stubs. 
Only the changed stubs need to be stored in this folder.
If the file does not exist there, it will still be taken from Workshop Module stubs folder.
Config files needs to be re-published with force attribute.
When PR is accepted, I will also PR the Documentation.
=> Add custom stubs folder

Modules/Workshop/Scaffold/Module/Generators/Generator.php, Modules/Workshop/Tests/ModuleScaffoldTest.php
When you try to create a module with a name like "julientant/some-stuff", the module generator will work just fine but the workshop part will because because it does not sanitize the module name.
=> Fix broken workshop when module name contains dash

docker-compose.yml
The goal of this PR is to restore the default/standards ports into the docker-compose.yml file, so that : 
- HTTP is exposed on port 80
- MySQL is exposed on port 3306
I also renamed the default network to add some Asgard swag 😎
=> Use standard ports in docker-compose + rename network

app/Exceptions/Handler.php
I've been meaning to fix this for quite a long time...
=> Fix TokenMismatchException not being handled if `app.debug` is `false`

Modules/Core/Resources/views/components/i18n/textarea.blade.php, Modules/Core/Resources/views/components/textarea.blade.php
Without this, it is impossible to add custom config to a single CKEditor instance since `CKEDITOR.replace()` uses the `id` of the field, not the name.
=> Add missing `id` attribute to editor's textarea

Modules/Core/macros.php, Modules/Translation/Http/Controllers/Admin/TranslationController.php, Modules/Translation/Http/Controllers/Api/TranslationController.php, Modules/Translation/Resources/lang/translation/en/translations.php, Modules/Translation/Resources/views/admin/translations/partials/revision.blade.php, Modules/Translation/Services/TranslationRevisions.php
TranslationController is mixture of HTML code.
The controller is doing too much work for revisions and also heredoc inside the controller is messy as hell.
All revision formatting stuff is now abstracted into another class and revision template is moved into a blade partial.
Exporting data into CSV file is pretty common. so maybe it will be a good idea to make a macro for that. so that user can export CSV file in a fluent interface.
=> Make TranslationController slim

Modules/User/Entities/Sentinel/User.php, config/asgard/user/config.php
user can create dynamic relations without accepting the user object as a parameter.  now `$this` in closure will refer to the User object.
```php
'extension' => function () {
return $this->belongsTo(UserExtension::class, 'user_id', 'id')->first();
}
```
=> Bind current object to the dynamic relations closure

Modules/Page/Http/Requests/CreatePageRequest.php, Modules/Page/Http/Requests/UpdatePageRequest.php, Modules/Translation/Resources/lang/page/de/messages.php, Modules/Translation/Resources/lang/page/en/messages.php, Modules/Translation/Resources/lang/page/fr/messages.php, Modules/Translation/Resources/lang/page/nl/messages.php
The slug field is set as "NOT NULL" in the database, we have to make sure that the field is filled before creating/updating the page model.
=> Slug is required in page module

Modules/Core/Console/Installers/Scripts/ProtectInstaller.php
Tell users about the -f force flag for the asgard installer if the .…env file already exists.
Just adding helpful messaging for new users...
=> Tell users about the -f force flag for the asgard installer 

Modules/Core/Console/Installers/Scripts/UserProviders/ProviderInstaller.php
Setting up the admin user can take a while and it is not clear that the installer is still running, particularly if you are trying to do lots of things at once. A small change to the messaging would make  it clear  that the install process isn't quite finished.
=> Update the message displayed while the admin user is created.

Modules/Core/Console/InstallCommand.php, Modules/Core/Console/Installers/Scripts/ConfigureAppUrl.php
Add additional install script to prompt for APP_URL when gathering information to create the .env file
Give users the opportunity to set the APP_URL to something other than localhost, lots (most?) people run multiple sites in their local development servers.
=> Add additional install script to prompt for APP_URL

Modules/Setting/Blade/SettingDirective.php
Currently the output of the `@setting` blade directive is unescaped.
This currently impacts the site meta description, if it is set to something containing a `"` it will break out of the meta description tag:
https://github.com/AsgardCms/Platform/blob/3.0/Themes/Flatly/views/layouts/master.blade.php#L6
With the `site-description` setting set to `A description containing "quotes" will break` will cause:
```
<meta name="description" content="@setting('core::site-description')" />
```
to become
```
<meta name="description" content="A description containing "quotes" will break" />
```
=> Escaped the output of the @setting blade directive

Modules/User/Presenters/UserPresenter.php
The use of protocol relative URLs (`//example.org/alpha`) is now considered an anti-pattern.
> Now that SSL is encouraged for everyone and doesn’t have performance concerns, this technique is now an anti-pattern. If the asset you need is available on SSL, then always use the https:// asset. 
From https://www.paulirish.com/2010/the-protocol-relative-url/
=> Explicitly used https to request the users Gravatar icon

Modules/User/Http/Requests/RolesRequest.php
The unique validation for role slugs was not ignoring the current role preventing roles from being updated
=> Role Slug Unique Validation Fix

Modules/Media/Repositories/Eloquent/EloquentFileRepository.php, Modules/Media/Tests/EloquentFileRepositoryTest.php
This fixes an edge case where `getNewUniqueFilename()` can output a filename that already exists
=> Generated Numeric File Name Suffixes Are Not Always Unique

Themes/Adminlte/views/layouts/master.blade.php
Without the `cluster` and `encrypted` options, Pusher returns errors.
=> Upgrade Pusher client

Modules/Core/Console/Installers/Scripts/SetAppKey.php
The `getLaravel()` method called by the `ConfirmableTrait` doesn't exist on the `SetEnv` installer, so it's been overridden and uses an instance of the `Application` to decide whether it should show the `You are running in Production!` warning.
Fixes issue #432
=> Define the warning callback on the SetAppKey

Modules/Setting/Support/Settings.php, Modules/Setting/Tests/SettingsTest.php
This is the same as #435, but backported to Asgard 2
=> [2.0] Fix settings with falsey values not getting returned

Modules/User/Repositories/Sentinel/SentinelAuthentication.php
Fix #467 
Fix error below
```
In SentinelAuthentication.php line 171:
Trying to get property of non-object
```
=> Fix issue#467 id() method checks null instead of false

Modules/Core/helpers.php, Modules/Tag/Tests/Integration/TaggableTraitTest.php, Modules/Tag/Traits/TaggableTrait.php
Fix for Issue #455 (Adding support for UTF-8 slug)
=> Fix for Issue #455 (Adding support for UTF-8 slug)

Modules/Menu/Providers/MenuServiceProvider.php
The URIs that are generated for the menu items aren't passed through Laravel Localization and so can be generated incorrectly especially when settings like `hideDefaultLocaleInURL` are enabled.
=> Use LaravelLocalization When Generating Menu Item URIs

Modules/Core/Assets/js/mixins/ActiveEditor.js
The ActiveEditor.js doesn't refuse to load a custom editor anymore (Bugfix for #506).
=> custom backend editor fix

Modules/Tag/Tests/Integration/TaggableTraitTest.php, Modules/Tag/Traits/TaggableTrait.php
=> Set tags only if passed any.

Modules/Core/Providers/CoreServiceProvider.php
Hello @nWidart,
I don't know if this is a feature or a bug, but I think we should only watch the request path when we are deciding if the user is on backend.
When we are watching the whole URL the subdomains are also involved but than we are getting error, because the system wants to include some admin JS.
Best regards,
David.
refs #550
=> Fix for #550

Modules/Page/Http/Controllers/PublicController.php
=> Check page status if page exists.

Modules/Core/Config/core.php, Modules/Core/Providers/CoreServiceProvider.php, Modules/Core/Providers/RoutingServiceProvider.php, Modules/Media/Http/backendRoutes.php, Modules/Media/Providers/MediaServiceProvider.php, Modules/Menu/Http/backendRoutes.php, Modules/Menu/Providers/MenuServiceProvider.php, Modules/Page/Http/apiRoutes.php, Modules/Page/Http/backendRoutes.php, Modules/Page/Http/frontendRoutes.php, Modules/Page/Providers/PageServiceProvider.php, Modules/Tag/Http/backendRoutes.php, Modules/Tag/Providers/TagServiceProvider.php, Modules/Translation/Http/backendRoutes.php, Modules/Translation/Providers/TranslationServiceProvider.php, Modules/User/Http/apiRoutes.php, Modules/User/Http/backendRoutes.php, Modules/User/Providers/UserServiceProvider.php, Modules/Workshop/Http/backendRoutes.php, Modules/Workshop/Providers/WorkshopServiceProvider.php, config/asgard/core/core.php
Hi @nWidart,
This is my pull request in Asgard version 3.
Pull request in version 2: https://github.com/AsgardCms/Platform/pull/544
Please merge.
Thank you,
Huy Dang
=> fix route:cache and config:cache issue

Modules/Page/Http/Controllers/PublicController.php
This check if the request page match the locale and the slug. If do not match just do a 301 redirect so the user can see the correct page and the correct url, good for seo purpose.
Should fix: https://github.com/AsgardCms/Platform/issues/567
=> Check page slug and locale

Modules/Page/Http/Controllers/PublicController.php, Themes/Flatly/views/layouts/master.blade.php
This commit add canonical and alternate links for pages in each language.
Sorry for the first 2 commit, it was a mistake, the second just revert the first, the 3rd is correct
=> Add canonical and Alternate link

Modules/Setting/Resources/views/admin/fields/plain/radio.blade.php, Modules/Setting/Resources/views/admin/fields/translatable/radio.blade.php
If you create a new module and a settings.php file with the following:
~~~
return [
'default-optimizator' => [
'description' => 'mediaoptimization::settings.fields.titles.default',
'view' => 'radio',
'translatable' => false,
'options' => [
'Test' => 'Test',
'Dummy' => 'Dummy',
],
'default' => 'Dummy',
]
];
~~~
you can see that if you save the first radio in the DB the value is correct but the view checked the wrong radio, usually the last one.  
For some reason the problem was the casting, removing it will work like a charm.
=> Fixed a bug that checked the last radio even if wasn't the right one

Modules/User/Repositories/Sentinel/SentinelUserRepository.php
Thank you to @chiragpipariya for his initial fix in #586.
Looks like this was partially solved by fa264a79f7af1fae97b104455452e52c30895f63 (and another earlier commit that I cannot find right this moment).
=> Fix #583: `activated` vs `is_activated`

Modules/Media/Assets/js/components/MultipleMedia.vue, Modules/Media/Assets/js/components/SingleMedia.vue, Modules/Page/Assets/js/components/PageForm.vue
According to Vue, we should use kebab-case events. For more information, see here: https://vuejs.org/v2/guide/components-custom-events.html#Event-Names
I think it would be safe to assume in a future version of Vue that this will cause errors. We should fix it now while things are still relatively new.
=> Use kebab-case for events

composer.json
This PR adds `roave/security-advisories` as a dev dependency to help mitigate vulnerable code from being installed.
=> Adds Roave Vulnerability Checker Package

Modules/Menu/Repositories/Eloquent/EloquentMenuItemRepository.php
Because the `root` menu item is not active, Nestable Collection was removing all the menu items. Why this only showed up on the upgrade to Laravel 5.7, I have no idea…
=> Prevent nestable collection removing menu items

Modules/Setting/Resources/views/admin/fields/plain/number.blade.php, Modules/Setting/Resources/views/admin/fields/translatable/number.blade.php
In the number fields there is no possibility to define `min`, `max` or `step` because the options are hard coded.  
I have added default options array that wil lbe merged with the options added by user.  
In this way the user can add a `options` array to define what he need.
For example, lets assume we have this options settings:
```
'invoice_default_tax' => [
'description' => trans('invoice::settings.form.default_tax'),
'view' => 'number',
'translatable' => false,
'options' => [
'min' => 10,
'max' => 30,
'step' => 0.1
]
],
```
it will be merged with the default and now in the setting the input is much more useful.
Please review if it works, the same logic can be applied to the other fields
=> Add possibility to define some options on number field

Modules/Media/Assets/js/components/MediaList.vue, Modules/Media/Assets/js/components/NewFolder.vue, Modules/Media/Assets/js/components/UploadZone.vue, Modules/Translation/Resources/lang/media/en/media.php
This replaces the upload files button with an action that slides open the "drop zone" for dropping files.
Quite a few code style changes...not all of them required by ESLint.
Also included:
- I increased the width of the action buttons so they don't freak out and break on smaller screen sizes.
- I moved all the action buttons not in a button group into their own button group to fix the OCD-inducing 2 pixel offset between them and the other buttons.
=> Reimplement drag-n-drop media upload

Modules/User/Repositories/Sentinel/SentinelAuthentication.php
I have edited the `Modules/User/Repositories/Sentinel/SentinelAuthentication.php` file adding some return types and I have used the `getUser` method instead of `check` method to retrieve the user.  
Reading Sentinel documentation looks like that both of them return the user object but I think that getUser is much more readable and understandable
Any tought?
=> Added return type and used getUser function instead of check

Modules/Core/Traits/NamespacedEntity.php, Modules/Tag/Contracts/TaggableInterface.php, Modules/Tag/Traits/TaggableTrait.php
Also fixed a potential race condition where adding (or removing) two of the same tag could cause an exception. I've never had a user complain of this, but I did manage to break it myself on purpose.
In addition, I simplified the methods which accepted a string or array by using Laravel's `array_wrap` to make sure they were an array.
And of course, various clean-ups and code sniffer fixes.
=> Update Tags trait with typehints

Modules/Core/Assets/js/components/CkEditor.vue, Themes/Adminlte/views/layouts/master.blade.php
Right now, there is no config applied, unless you manually pass it via the `config` param. This sets the default (if the `config` param was not supplied) to use the custom CKEditor config file, if there is one.
=> Allow CKEditor custom config to work in Vue component

Modules/Media/Assets/js/components/MediaList.vue, Modules/Page/Assets/js/components/PageTableServerSide.vue, Modules/User/Assets/js/components/RoleTable.vue, Modules/User/Assets/js/components/UserTable.vue
10 seems to be so small, especially in the media list
=> Set default page length to 30 for tables

Modules/Page/Assets/js/components/PageForm.vue, Modules/Translation/Resources/lang/page/en/pages.php
I'm not sure what the best wording would be, but I have had several users complain about the current ambiguous wording.
=> Rename the label for the status checkbox to make it less ambiguous

Modules/Media/Assets/js/components/MediaList.vue
Sometimes the directory won’t load, or thumbnails won’t show… Various other weird glitches, too. The `data` -> `media` variable name change is probably just a placebo.
=> Attempt to fix weird glitches with MediaList

Modules/Dashboard/Http/Controllers/Admin/DashboardController.php
This PR is about the issue pointed out on slack, here the references: https://asgardcms.slack.com/archives/C043NPXKQ/p1541563026016400
Since the construct is executed before the middlewares, this will prevent the bootWidgets() from being executed before the permissions checks
=> Prevent the bootWidgets() from being executed before middlewares checks

Modules/Core/Http/Middleware/LocaleSessionRedirectMiddleware.php, Modules/Core/Providers/CoreServiceProvider.php, Modules/Core/Providers/RoutingServiceProvider.php
Hi,
This version is using version 1.3.* of mcamara/laravel-localization
https://github.com/AsgardCms/Platform/blob/master/Modules/Core/composer.json#L29
Since a few time, the logic to add the locale prefix is not anymore on the localizationRedirect 
https://github.com/mcamara/laravel-localization/blob/master/src/Mcamara/LaravelLocalization/Middleware/LaravelLocalizationRedirectFilter.php
But on LocaleSessionRedirect instead
https://github.com/mcamara/laravel-localization/blob/master/src/Mcamara/LaravelLocalization/Middleware/LocaleSessionRedirect.php
=> Change due to version 1.3 of laravel-localization

Modules/Menu/Http/Controllers/Admin/MenuItemController.php
This also means that when you edit and save a menu item, it gets moved out of its parent to the root of the menu.
I've narrowed this down to this point: [TypiCMS/NestableCollection/src/NestableCollection.php#L66](https://github.com/TypiCMS/NestableCollection/blob/447736c3de72dc6ba994b9e339c203e35d13999e/src/NestableCollection.php#L66) (actual function here: [TypiCMS/NestableCollection/src/NestableCollection.php#L162-L181](https://github.com/TypiCMS/NestableCollection/blob/447736c3de72dc6ba994b9e339c203e35d13999e/src/NestableCollection.php#L162-L181))
I am unable to figure out why this is removing ALL menu items, even if they do have a parent...
=> Fix menu item parents not being loaded into dropdown

Modules/Translation/Repositories/LocaleRepository.php
Currently, there is an exception:
```
Declaration of Modules\Translation\Repositories\Eloquent\EloquentLocaleRepository::translatableLocales(): Illuminate\Support\Collection must be compatible with Modules\Translation\Repositories\LocaleRepository::translatableLocales(array $locales = NULL): Illuminate\Support\Collection
```
Contract: https://github.com/AsgardCms/Platform/blob/265d5cf16d3e005c07a7672aea3d6a724fd37fcc/Modules/Translation/Repositories/LocaleRepository.php#L38
Implementation: https://github.com/AsgardCms/Platform/blob/265d5cf16d3e005c07a7672aea3d6a724fd37fcc/Modules/Translation/Repositories/Eloquent/EloquentLocaleRepository.php#L89
=> Fix mismatched implementation from PR #702

composer.json
Roave/SecurityAdvisories conflict with `"league/commonmark": "<0.18.3"` so we need to update it for install with composer
=> Update `league/commonmark` to `^0.19`

Modules/Media/Repositories/Eloquent/EloquentFolderRepository.php
prevent deletion of folders that are NOT actually subfolders and only
start with the same sequence of characters. Originally, if I have two
or more folders on the same level:
`slider`
`slider-homepage`
and I delete only the `slider` one, `slider-homepage` would get deleted
as well.
This change makes sure the deleted folders are actually subfolders of
the deleted one.
=> fix folder deletion bug (#715)

Modules/User/Assets/js/components/AsgardPermissions.vue, public/js/app.js
The dot notation doesn't work mixed with the brackets.
Not sure how I missed this before...
=> Fix errors on permissions forms (Users and Roles)

Modules/Media/Blade/MediaMultipleDirective.php, Modules/Media/Blade/MediaSingleDirective.php
In PHP 7.3 `compact` no longer silently discards unset variables: https://www.php.net/manual/en/function.compact.php#refsect1-function.compact-changelog
=> Fix `compact` errors in PHP 7.3

docker/app/Dockerfile
The package `league/commonmark` needs `php ^7.1` from version `0.19.0` which is updated in the `composer.json` since d717670bcd7c10554555befb944eb734bd971ae9. However the `Dockerfile` has not been updated and cannot perform a `composer install` because the PHP version is only `7.0` which is too low for `league/commonmark`.
I would happily update the documentation pages as well if you want me to :)
The PHP 7.0 or higher part is no longer a valid requirement in the [Minimum System Requirements section](https://asgardcms.com/docs/v3/getting-started/installation#minimum-system-requirements).
I've noticed that the documentation only mentions to run `dcp up` and `dcp artisan asgard:install` in the [Install section](https://asgardcms.com/docs/v3/getting-started/docker#install-asgardcms) although …
=> Update php version in app docker image to 7.1

Modules/Core/Repositories/Cache/BaseCacheDecorator.php
Since the remember method could be used for a lot of different reason and to store different information for a different amount of time the best think is allow user to define the amount of time.
Right not the whole cache decorator use the same amount of time for each store.
I think that in this way we can manage cache with much more flexibility.
=> Allow set cache time on remember function

Modules/Media/Tests/MaxFolderSizeRuleTest.php
It looks like at some point the image's size was increased somehow. That's my only guess since the mocked folder size went down in my testing (I dumped all the things from the validator 😆).
I also noted the size of the mocked image, so we can watch it over time.
=> Fix folder size test

.travis.yml, composer.json, overrides/Illuminate/Http/Resources/DelegatesToResource.php
=> Allow PHP 7.4

config/app.php
I apparently forgot about this and didn't submit the PR... Ugh.
In February, someone was able to grab my Postmark credentials from a Google search and sent about 10,000 spam messages. They were able to do this because I had debug mode on and an error on a page that Google apparently crawled and cached.
This PR prevents certain environment variables (as well as POST data) from being displayed on Whoops.
I have been running this in production since February with no more incidents of credential leakage.
=> Prevent environment variable leakage when debug is on

Modules/User/Http/Controllers/Api/ApiKeysController.php, Modules/User/Http/Requests/DeleteUserTokenRequest.php, Modules/User/changelog.yml
This PR adds validation to prevent users from deleting API tokens that don't belong to them
=> Prevent Cross User Token Deletion

Modules/Workshop/Resources/views/admin/modules/partials/changelog.blade.php
This PR fixes the module/theme changelog views. It was calling `str_contains` which is now defined in `Symfony\Polyfill\Php80` and does not accept an array as the second argument like the Laravel helper function did.
=> Fixes Changelog Views

Modules/Translation/Repositories/Cache/CacheLocaleDecorator.php
Tried to update a site today to get the recent changes and had this error:
```
PHP Fatal error:  Class Modules\Translation\Repositories\Cache\CacheLocaleDecorator contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Modules\Translation\Repositories\LocaleRepository::listLocalesForSelect)
```
This PR adds the missing method to the cache decorator.
=> Add missing method to Locales cache decorator

Modules/Menu/Tests/MenuItemUriGeneratorTest.php
Fix: MenuItemUriGeneratorTest.php not using the generated $menuitem id.
Fix: MenuItemUriGeneratorTest.php - We can't fake events (They are required by Laravel Translatable to add translations).
=> Fix: MenuItemUriGeneratorTest.php not using the generated $menuitem id.

Modules/Workshop/Resources/views/admin/modules/show.blade.php, Modules/Workshop/Resources/views/admin/themes/show.blade.php
Fixes the styles of Module/Theme version in Workshop module
Previous style (Currently looks crooked in Themes):
New style (Nicer in general for both Themes/Modules):
=> Fixes alignment of Module/Theme version

Modules/Media/Assets/js/components/MediaList.vue, Modules/Media/Assets/js/components/MultipleMedia.vue, Modules/Media/Assets/js/components/SingleMedia.vue, public/js/app.js
This fixes the close button that isn't clickable in the select media dialog.
When an Element UI Dialog doesn't have a title, the title DIV collapses and the close button is overlapped by the content below it.
I've added a proper dialog title, instead of using the H4 in the dialog content.
Example of overlap (blue is overlapping DIV outline using devtools):
=> Fixes close button on single/multiple media browse dialog

Themes/Adminlte/views/layouts/master.blade.php
`<base href="{{ url()->current() }}">` cause this meta specify the base for all links also anchor https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
And if it only `url()`, we have wrong urls in languages tab and other anchors, with a buggy behavior
=> Theme/AdminLTE - meta base tag must specify the base for all relative

Modules/Translation/Resources/lang/user/en/users.php, Modules/User/Http/Controllers/Admin/Account/ApiKeysController.php, Modules/User/Http/Controllers/Api/ApiKeysController.php, Modules/User/changelog.yml
This PR prevents users from deleting their last API key as doing so causes most of the backend to stop working correctly.
=> Prevent Last API Key Deletion
