resources/views/asgard/user/public/login.blade.php

autofocus email field on login page

---

public/modules/Media/js/init-dropzone.js

See asgardcms/media#14 for more info.

Fix early redirect when uploading multiple files

---

app/Providers/RouteServiceProvider.php
config/app.php

Updated the position of
`App\Providers\RouteServiceProvider::class`
ServiceProvider, allowing to override each routes of the modules directory.
Hope it is helpful to others too.

Routes override

---

Modules/Workshop/Scaffold/Module/stubs/admin-controller.stub
Modules/Workshop/Scaffold/Module/stubs/create-table-migration.stub
Modules/Workshop/Scaffold/Module/stubs/create-translation-table-migration.stub

This is from https://github.com/AsgardCms/Workshop/pull/32

Use PSR-2 for Workshop stubs

---

Modules/User/Http/Controllers/Admin/UserController.php
Modules/User/Resources/views/admin/users/edit.blade.php

Allows developer to let users edit their own profile without having an error upon saving because they cannot list all users.

Add "Update and Back" button to User edit

---

Modules/Core/macros.php

Also run CS fixer on macros file

Add i18nInputOfType macro to match new normalInputOfType from #247

---

Modules/User/Repositories/Sentinel/SentinelUserRepository.php

Makes method consistent with the other `create*` methods

[Hotfix] Return User when creating with roles

---

Modules/Setting/Repositories/Eloquent/EloquentSettingRepository.php
Modules/Setting/Resources/views/admin/fields/plain/number.blade.php
Modules/Setting/Resources/views/admin/fields/plain/text.blade.php
Modules/Setting/Resources/views/admin/fields/plain/textarea.blade.php
Modules/Setting/Resources/views/admin/fields/plain/wysiwyg.blade.php
Modules/Setting/Resources/views/admin/fields/translatable/number.blade.php
Modules/Setting/Resources/views/admin/fields/translatable/text.blade.php
Modules/Setting/Resources/views/admin/fields/translatable/textarea.blade.php
Modules/Setting/Resources/views/admin/fields/translatable/wysiwyg.blade.php

- Checking on field database plainvalue not to be null (string null still supported)
- Change flag on SettingWasUpdated to false

Additional check for null in database

---

Modules/Core/macros.php

Fix normalInput and normalInputOfType setting value to '1' instead of value

---

config/modules.php

We can either do it here or on [laravel-modules](https://github.com/nWidart/laravel-modules). I elected for here because I don't know how many other users of laravel-modules there are beside Asgard, and I didn't want to cause any huge problems for them.

Fix emails generating in the wrong directory

---

Modules/User/Repositories/Sentinel/SentinelUserRepository.php

Fix comes from @nWidart via Slack, because he's awesome like that. 👍

Fix errors when data doesn’t contain a password field

---

Modules/Translation/Resources/lang/core/en/core.php
app/Exceptions/Handler.php

Method found here: https://slimcoding.com/laravel/how-to-handle-an-expired-csrf-token-nicely-in-laravel

Add more graceful handling of TokenMismatchException

---

Modules/Core/Console/Installers/Scripts/ConfigureDatabase.php
Modules/Core/Console/Installers/Writers/EnvFileWriter.php

With this changes, it's possible to define another database driver.
It's now also possible to change the port.
Moved from https://github.com/AsgardCms/Core/pull/103

Allow other database drivers

---

Modules/Media/Blade/MediaMultipleDirective.php
Modules/Media/Blade/MediaSingleDirective.php
Modules/Media/Resources/views/admin/fields/new-file-link-multiple.blade.php
Modules/Media/Resources/views/admin/fields/new-file-link-single.blade.php

The Tags Blade Directive uses $name as an argument for the Field Name in the View.
With this change, the $name attribute will be added to the Media Blade Directives.
If no $name argument is given, the zone name will be changed to $name in Directive, instead of in the view.

Using field name for both Media Blade Directives

---

Modules/Media/Blade/MediaSingleDirective.php

Correcting Error in MediaSingleDirective.php

---

docker-compose.yml
docker/app/Dockerfile
docker/app/default

This PR adds a self-signed certificate to the app image, so we can use HTTPS !

Docker : support HTTPS

---

Modules/Dashboard/Resources/views/admin/dashboard.blade.php

Edit grid error solution

---

Themes/Adminlte/views/partials/top-nav.blade.php

This adds escaping to the users full name in the header bar preventing a stored XSS exploit

Users Full Name Stored XSS Vulnerability

---

Modules/Translation/Resources/lang/user/en/roles.php

this change makes the label more clear for newcomers

Change label Inherit to Inherit from role

---

config/broadcasting.php

Laravel 5.5 & Pusher apparently changed things around a bit... Yay breaking changes. 🤣

Update Pusher configuration

---

composer.json

Group Tinker with Framework

---

Modules/Media/Http/Requests/CreateFolderRequest.php

This adds validation of folder names, preventing duplicates from being created

Media Unique Folder Names Validation

---

Modules/Page/Assets/js/components/PageTableServerSide.vue
public/js/app.js

We'll tackle sorting in another PR... >.>

Fix Page status column width

---

Modules/Media/Http/Requests/CreateFolderRequest.php

Added validation for folder names. Fixes #404

---

Modules/Media/Http/Controllers/Api/MediaController.php

Modify media controller to use Imagy non-statically (Fix issue #477)

---

Modules/Workshop/Manager/StylistThemeManager.php

Fix Issue #451 
Only check the last part of the path.

Fix for #451

---

Modules/Core/Repositories/Eloquent/EloquentBaseRepository.php

I've created PR with shorter code
issue #487

Fix issue #487 (allWithBuilder error)

---

Modules/Menu/composer.json

Updating typicms/nestablecollection package

---

Modules/Translation/Resources/lang/dashboard/pl/dashboard.php

Add polish translation for Dashboard module.

---

Modules/Translation/Resources/lang/translation/pl/translations.php

Add polish translation for Translation module.

---

Modules/Translation/Resources/lang/tag/pl/tags.php

Add polish translation for Tags module.

---

Modules/Translation/Resources/lang/setting/pl/messages.php
Modules/Translation/Resources/lang/setting/pl/settings.php

Add polish translation for Settings module.

---

Modules/Translation/Resources/lang/notification/pl/messages.php

Add polish translation for Notification module.

---

Modules/Translation/Resources/lang/menu/pl/menu-items.php
Modules/Translation/Resources/lang/menu/pl/menu.php
Modules/Translation/Resources/lang/menu/pl/messages.php
Modules/Translation/Resources/lang/menu/pl/validation.php

Add polish translation for Menu module.

---

Modules/Translation/Resources/lang/media/pl/folders.php
Modules/Translation/Resources/lang/media/pl/media.php
Modules/Translation/Resources/lang/media/pl/messages.php

Add polish translation for Media modules.

---

Modules/Translation/Resources/lang/workshop/pl/modules.php
Modules/Translation/Resources/lang/workshop/pl/themes.php
Modules/Translation/Resources/lang/workshop/pl/workbench.php
Modules/Translation/Resources/lang/workshop/pl/workshop.php

Add polish translation for Workshop module.

---

Modules/Setting/Entities/Setting.php
Modules/Setting/Events/SettingWasCreated.php
Modules/Setting/Events/SettingWasUpdated.php
Modules/Setting/Repositories/Eloquent/EloquentSettingRepository.php
Modules/Setting/Resources/views/admin/fields/plain/media-single.blade.php
Modules/Setting/Resources/views/admin/fields/translatable/media-single.blade.php
Modules/Setting/Support/Settings.php
Modules/Setting/Tests/BaseSettingTest.php

[Setting Module] Add view type media-single

---

Modules/Core/Http/Middleware/Authorization.php

In case of accepts json then instead of redirecting sending unauthorised response

In case of accepts json then instead of redirecting sending unauthorised response

---

Modules/Page/Entities/Page.php

Due to this function images can show in frontend and admin both.

Added Image Attribute

---

Modules/Core/macros.php

HI 
i'm added two below function 
i18nFile & normalFile
Because while we installing new asgardcms we lost many thing, 
so i think those function are required. 
can you please update this file ?

i18nFile & normalFile added two function

---

Modules/Media/Assets/js/components/MultipleMedia.vue
Modules/Media/Assets/js/mixins/MultipleFileSelector.js
Modules/Media/Http/Controllers/Api/MediaController.php
Modules/Media/Http/apiRoutes.php

Hi,
Clean up version of Vuejs component: Multiple file selector #523,  all credit goes to @daothanh

Vuejs component: Multiple file selector clean up of 523

---

Modules/Core/Providers/RoutingServiceProvider.php
Modules/Core/changelog.yml
Modules/Media/Assets/js/components/SingleMedia.vue
Modules/Media/Assets/js/mixins/MultipleFileSelector.js
Modules/Media/Assets/js/mixins/RandomString.js
Modules/Media/Assets/js/mixins/SingleFileSelector.js
Modules/Setting/Resources/views/admin/fields/plain/number.blade.php
Modules/Setting/Resources/views/admin/fields/plain/text.blade.php
Modules/Setting/Resources/views/admin/fields/plain/textarea.blade.php
Modules/Setting/Resources/views/admin/fields/translatable/number.blade.php
Modules/Setting/Resources/views/admin/fields/translatable/text.blade.php
Modules/Setting/Resources/views/admin/fields/translatable/textarea.blade.php
Modules/Translation/Resources/lang/page/de/pages.php
Modules/Workshop/Providers/WorkshopServiceProvider.php
Modules/Workshop/Scaffold/Module/ModuleScaffold.php
Modules/Workshop/Scaffold/Theme/stubs/themeJson.stub
Modules/Workshop/Tests/ModuleScaffoldTest.php
Modules/Workshop/Tests/ThemeScaffoldTest.php
Modules/Workshop/changelog.yml
config/modules.php
public/modules/media/js/components/MultipleMedia.vue
public/modules/media/js/mixins/MultipleFileSelector.js

This should also include #597.

Merge 3.0 into master

---

app/Providers/AppServiceProvider.php

Remove explicit registration of debugbar

---

Themes/Adminlte/views/layouts/master.blade.php

This PR adds an SRI check for the 3rd party pusher asset.
To achieve this I have had to fix the version to exactly 4.1.0

Adds SRI For Pusher Asset

---

dcp

This PR is the same as #608 but from master

Use Env When Defining The Hashbang

---

composer.json

This PR is the same as #606 but targets the master branch

Adds Roave Vulnerability Checker Package

---

.github/CONTRIBUTING.md

This PR adds a CONTRIBUTING file which contains a link to the instructions on the docs page

Adds Contributing File

---

Modules/Tag/Assets/js/components/TagInput.vue

Also, allow the Label to be modified; code style too.
I'm still looking into how we can do the same for tab key, but so far no luck. At least this way, users don't have to remove their fingers from the keyboard to click an option.

Allow first tag to be selected on enter key

---

Modules/User/Transformers/FullRoleTransformer.php

Only add the delete url if there is a user id is present

---

Modules/Media/Image/Intervention/Manipulations/ResizeCanvas.php

Missing ResizeCanvas.php

---

Modules/Core/Repositories/BaseRepository.php
Modules/Core/Repositories/Cache/BaseCacheDecorator.php
Modules/Core/Repositories/Eloquent/EloquentBaseRepository.php
Modules/Workshop/Scaffold/Module/stubs/module-service-provider.stub

Added where() and with() to EloquentBaseRepository.
A couple of times I found myself in need of those methods in my models repositories and had to write and copy/paste.
Having these in the EloquentBaseRepository made it more consistent and less error prone.

added where() and with() to EloquentBaseRepository

---

Modules/Workshop/Scaffold/Module/stubs/module-service-provider.stub

edited module-service-provider.stub to load module's factories

---

Themes/Adminlte/assets/vendor/admin-lte/dist/css/AdminLTE.css
Themes/Adminlte/views/partials/top-nav.blade.php
config/asgard/core/core.php
public/themes/adminlte/vendor/admin-lte/dist/css/AdminLTE.css

Only two changes need to be made. One, we had to fix the "bars" for showing and hiding the left sidebar. Two, we had to fix the size and position of the arrow on dropdown items in the sidebar.

Upgrade to Font Awesome 5

---

composer.json

See here: https://github.com/FriendsOfPHP/security-advisories/blob/master/league/commonmark/2019-03-21.yaml

Upgrade league/commonmark to avoid security advisory

---

.travis.yml

I'm not sure if we'll get any failures (besides the `MaxFolderSize` test, LOL), but here it is.

Also run tests on PHP 7.3

---

Modules/Media/Assets/js/components/MediaList.vue

Media Module List Buttons are shown uneven so we corrected. please check and approve so we can used in next version properly.
Thanks.

Few design issues that we found and corrected from our side

---

Modules/Media/Assets/js/components/MediaList.vue
public/js/app.js

Same with the permissions issue (#722), not sure how I missed this. I even thanked shu for finding the fix!

Fix MediaList errors

---

Modules/User/Assets/js/components/AsgardPermissions.vue
public/js/app.js
public/modules/user/js/components/AsgardPermissions.vue

I really should check my work before creating PRs... 🙄

Fix permissions (again)

---

Modules/User/Assets/js/components/AsgardPermissions.vue
public/js/app.js
public/modules/media/js/components/MediaList.vue
public/modules/user/js/components/AsgardPermissions.vue

So... Here we are again...
I tested it for real this time, rather than just knee-jerk fixing the syntax like last time.
I also published module & theme assets.

Fix permissions, maybe for good

---

Modules/Page/Assets/js/components/PageForm.vue
Modules/Translation/Resources/lang/page/en/pages.php

This refers to #675. See it for images

Change status label and checkbox and make it much more understandable

---

Modules/Core/Assets/js/components/FormErrors.vue
public/js/app.js
public/modules/core/js/components/FormErrors.vue

Now I remember why I sat on it for so long... I wasn't finished and didn't have time to work on it. 😨

Fix FormErrors component

---

Modules/Core/Assets/js/components/CkEditor.vue

Fix for https://github.com/AsgardCms/Platform/issues/495

Updating VueCKEditor

---

Modules/Core/Assets/js/components/CkEditor.vue

This should have everything from #750 while also keeping in line with the changes that have been made to `master` since it diverged from `3.0`.
I have NOT tested this (nor have I tested the changes in `3.0`), so I'm not sure if this works. I will hopefully have some time to test this in the next few days.

CKEditor updates from #750

---

Modules/Core/Internationalisation/Translatable.php
Modules/Core/composer.json
Modules/Media/Entities/File.php
Modules/Menu/Entities/Menu.php
Modules/Menu/Entities/Menuitem.php
Modules/Page/Entities/Page.php
Modules/Setting/Entities/Setting.php
Modules/Tag/Entities/Tag.php
Modules/Translation/Entities/Translation.php
Modules/Workshop/Scaffold/Module/stubs/entity-eloquent.stub

composer updated and replaced all namespaces and usage

App/Laravel - Dimsav/Translatable become Astrotomic/Translatable

---

Modules/Setting/Tests/BaseSettingTest.php

Fix for broken tests from #771. There are still some broken tests from the Menu module that I am trying to track down, but this is a start.

Fix Setting module tests

---

Modules/Translation/Providers/TranslationServiceProvider.php
Modules/Translation/Repositories/Cache/CacheLocaleDecorator.php

added cache decorator to LocaleRepository

---

Modules/User/Repositories/Eloquent/EloquentUserTokenRepository.php

This PR removes a potential infinite loop when creating an API key

Removes Potential Infinite Loop

---

Modules/Media/Tests/ThumbnailTest.php
Modules/Media/Tests/ThumbnailsManagerTest.php

This PR fixes namespaces of a couple of tests in the Media module to comply with PSR4

Media Test PSR4 Fix

---

Modules/Media/Assets/js/components/MediaForm.vue
Modules/Menu/Resources/views/admin/menuitems/edit.blade.php
Modules/Menu/Resources/views/admin/menus/edit.blade.php
Modules/Page/Assets/js/components/PageForm.vue
public/js/app.js

Flag icons to Media and Page form tabs

Page/Media - Added flag-icon to el-tab-pane languages

---

Modules/Translation/Resources/lang/user/en/users.php
Modules/User/Assets/js/components/UserForm.vue
public/js/app.js
public/modules/user/js/components/UserForm.vue

This PR corrects the roles input label which showed "Password" before.

Fixes Incorrect Label
